apiVersion: v1
kind: Pod
metadata:
  name: configmap-printer-pod
spec:
  containers:
    - name: configmap-data-printer
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "echo name: $(name_env) password: $(password_env) " ]
      env:
        - name: name_env
          valueFrom:
            configMapKeyRef:
              name: configmap-demo
              key: name
        - name: password_env
          valueFrom:
            configMapKeyRef:
              name: configmap-demo
              key: password
  restartPolicy: Never