apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: printenv-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: printenv-cronjob
            image: alpine
            command: ["printenv"]
          restartPolicy: Never
