apiVersion: batch/v1
kind: Job
metadata:
  name: printenv-job
spec:
  template:
    spec:
      containers:
      - name: printenv-job
        image: alpine
        command: ["printenv"]
      restartPolicy: Never
  backoffLimit: 4