apiVersion: v1
kind: Pod
metadata:
  name: secret-printer-pod
spec:
  containers:
    - name: secret-data-printer
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "echo name: $(name_env) password: $(password_env) "]
      env:
        - name: name_env
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: name
        - name: password_env
          valueFrom:
            secretKeyRef:
              name: secret-demo
              key: password
  restartPolicy: Never